spring.application.name=desafio_tecnico
server.port=8001

# Database Connection URL
spring.datasource.url=jdbc:postgresql://localhost:5432/to-do-list

# Database Credentials
spring.datasource.username=${POSTGRESUSR}
spring.datasource.password=${POSTGRESPWD}

# PostgreSQL Driver Class (Optional in newer Spring Boot versions, as it's auto-detected)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update